### PR TITLE
#12 - fixed copyrights section

### PR DESCRIPTION
**Pull request by RomanKisilenko**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by dmarkov** [comment]
@krzyk it's yours, please review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk thanks, I just added **16 mins** to your account, payment `50342767`

+16 added to your rating, current score is: [+1978](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
