### PR TITLE
URISyntaxException in ClasspathMfs

### PR DESCRIPTION
**Pull request by thecrow69**
The original implementation which first transforms the resource URLs to URIs and then loop through the URIs to create the streams based on the toURL-method of the URIs leads to a problem in our environment. Our classpath contains spaces and that leads to a URISyntaxException when transforming the URL to an URI. Is there a reason for the double transformation?

### CODE REVIEW

**Comment by dmarkov** [comment]
@thecrow69 I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@dmzaytsev please review

**Comment by dmzaytsev** [comment]
@thecrow69 CI builds failed
please fix it

**Comment by dmzaytsev** [comment]
@thecrow69 please run Maven build before pushing the changes.
> $ mvn clean install -Pqulice

You will see some Checkstyle errors

**Comment by dmzaytsev** [comment]
@thecrow69 according our [quality rules[ (http://www.teamed.io/qa.html)
> Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

please add the link to the original ticket to the pull request description

**Comment by dmzaytsev** [comment]
@yegor256 I guess there is no ticket for this PR. What we should to do in this case?
I think you as the architect should accept the fixing issue before review, isn't it ?

**Comment by thecrow69** [comment]
You are right. I haven’t opened a ticket because I needed the source code to find the problem and had an idea how to fix it directly. So I fixed it for us and it worked fine. I wanted to contribute my solution to the community so I created the pull request. Sorry for not reading the guidelines completely before doing this.

Von: Dmitry Zaytsev [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. August 2015 12:55
An: jcabi/jcabi-manifests
Cc: Hoff, Oliver
Betreff: Re: [jcabi-manifests] URISyntaxException in ClasspathMfs (#26)


@yegor256<https://github.com/yegor256> I guess there is no ticket for this PR. What we should to do in this case?
I think you as the architect should accept the fixing issue before review, isn't it ?

**Comment by thecrow69** [comment]
Hi Dmitry,

I’ve fixed the formal problems. It builds now correctly.

Sorry!

Von: Dmitry Zaytsev [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. August 2015 12:31
An: jcabi/jcabi-manifests
Cc: Hoff, Oliver
Betreff: Re: [jcabi-manifests] URISyntaxException in ClasspathMfs (#26)


@thecrow69<https://github.com/thecrow69> please run Maven build before pushing the changes.

$ mvn clean install -Pqulice

You will see some Checkstyle errors

**Comment by dmzaytsev** [comment]
@thecrow69 many thanks for your contribution!
looks good,
but let's wait the architect decision.

**Comment by dmzaytsev** [comment]
@yegor256 please take a look
can we merge it?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@thecrow69 you should not touch this line in your branch: https://github.com/jcabi/jcabi-manifests/pull/26/files#diff-ed31ed22e802415e04fd5effd9870314R43

**Comment by thecrow69** [comment]
Sorry Yegor, I haven’t touch this line intentionally. Maybe my IDE has done this. I changed it back.

Von: Yegor Bugayenko [mailto:notifications@github.com]
Gesendet: Freitag, 7. August 2015 06:51
An: jcabi/jcabi-manifests
Cc: Hoff, Oliver
Betreff: Re: [jcabi-manifests] URISyntaxException in ClasspathMfs (#26)


@thecrow69<https://github.com/thecrow69> you should not touch this line in your branch: https://github.com/jcabi/jcabi-manifests/pull/26/files#diff-ed31ed22e802415e04fd5effd9870314R43

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@dmzaytsev Much obliged! I have added **22 mins** to your account in payment "62978483", 120 hours and 8 mins spent. you're getting extra minutes here (c=7). +22 to your rating, your total score is [+1699](http://www.netbout.com/b/35166?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
