### PR TITLE
#13 - specify new snapshot version on release

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@carlosmiranda this pull request is for you, please review

**Comment by carlosmiranda** [comment]
@rultor Can we merge now?

**Comment by dmarkov** [comment]
@carlosmiranda I added **19 mins** to your account, many thanks for working with the project!... +19 to your rating, your total score is [+1769](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
