### PR TITLE
correct word dependency

### PR DESCRIPTION
**Pull request by mishin**

### CODE REVIEW

**Comment by dmarkov** [comment]
@mishin Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@mishin thanks!

**Comment by dmarkov** [comment]
@yegor256 Many thanks! **16 mins** were added to your account in Transaction ID `000-b1a750b6` (task took 190 hours and 8 mins). extra minutes for review comments (c=1). +16 added to your rating, current score is: [+165](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
