### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Much obliged! I have added **16 mins** to your account in payment "000-1f6a9f63", 26 hours and 32 mins spent

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+4565](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
