### PR TITLE
#20

### PR DESCRIPTION
**Pull request by maurezen**
Removed obsolete declaration

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@longtimeago it's yours, please review

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge this

**Comment by longtimeago** [comment]
@rultor merge?

**Comment by dmarkov** [comment]
@longtimeago Thanks a lot, I just topped your account for **17 mins**, transaction ID `54681633`, total time was 49 hours and 9 mins. you're getting extra minutes here (c=2). +17 added to your rating, at the moment it is: [+3723](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
